### ISSUE TITLE
What should the eval function return when the parameters fail ?

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [aresio/fst-pso#12]
Hello Marco,

I was wondering, for FST-PSO to optimize parameters smoothly AND if the evaluation function is some noisy black box that can fail for some given parameters set (still within the defined searchable domains, but it's unpredictable that a given parameters set will fail), what value should be returned by the evaluation function ?

At the moment I am using the worst possible score that the evaluation function could return according to the defined searchable domains. I cannot figure out if this is the right/acceptable way, or if I should avoid returning an extreme value to (potentially) get a smoother, faster optimization. Is there a real impact that I should be aware of ?

Thank you very much for your advices !

**Comment by aresio** [comment]
Hi Charly,
sorry I missed this message. 

So, as you already imagined, handling such problematic solutions is tricky.

Of course, you do not want those solutions to interfere with the optimization, so the returned fitness should definitely be high; in particular, higher than the rest of the swarm. You could, in principle, use an extreme score (e.g., sys.float_info.max) because, in the fuzzy reasoner, the fitness values are "clamped" to the worst estimated fitness value. Such estimation is based on worst particle calculated during the first iteration of the algorithm. However, if you have the misfortune of having a "problematic" particle during the fist iteration, then the fuzzy reasoner would probably break down. Hence, my suggestion is to use a high fitness value for problematic particles but, possibly, not too large to not interfere with fuzzy reasoning.

It is an interesting research topic, by the way. Probably FST-PSO should be extended to explicitly cope with this situations (e.g., bypassing the fuzzy reasoner when the fitness cannot be properly calculated, or automatically repositioning the particle in a "better" region of the search space), it would be nice for a future version of the tool.

**Comment by CharlyEmpereurmot** [comment]
Thank you very much that was helpful :)
