### ISSUE TITLE
Library exits application on error

### ISSUE THREAD

**Issue by EliasHasle** [aresio/fst-pso#13]
Whenever the fitness function fails during initialization, `fst-pso` will exit the application without telling anything specific about what went wrong. I suggest instead raising an exception, and leaving the handling to the user. This will make it easier to debug fitness functions without writing dedicated testing applications.

**Comment by aresio** [comment]
Hi Elias,

yes, unfortunately FST-PSO cannot figure out what kind of issue was created by the fitness function. I agree with your idea, I will raise an Exception so that it can be handled by the user. 

However, I will change FST-PSO's behavior and make this control optional, bacause the automatic fitness check that I implemented is causing too many issues. 

I will implement your suggestion and publish the new version in a few days.

**Comment by EliasHasle** [comment]
Thank you very much! I think raising exceptions should, by similar reasoning, be the default behavior for other errors aswell.

It should be possible to at least forward the root exception, right? https://docs.python.org/3/tutorial/errors.html Hm, well, simply not wrapping the code in try-catch will let the exceptions through to the user, which is desirable compared to obscuring them.

**Comment by aresio** [comment]
As promised, I removed the try-catch around the fitness test. Moreover, if you specify the search space _before_ the fitness function, a more "realistic" particle (i.e., created inside the search space)  will be tested. In order to perform the test, you have to explicitly enable the test by passing the argument `skip_test=False`. 

I will extend exceptions to all error messages in the next release. Please let me know if everything works correcly!

**Comment by EliasHasle** [comment]
This is definitely an improvement. Thanks a lot for responding so fast. :-)
