### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by haskarb** [aresio/fst-pso#2]
I wanted to use this package but I am not able to install it. Could you tell us how to install it and its dependencies?

**Comment by aresio** [comment]
Dear Bhaskar,

of course, let's try to solve the issue.  First of all, please note that the current version of fst-pso only supports python 2.

fst-pso has two main dependencies:
- numpy
- pyfuzzy 

The first one should be easy to solve. The second one is trickier, because you need to install the ANTLR3 python runtime first*. The ANTLR3 python runtime can be downloaded from GITHUB at the following address:

https://github.com/antlr/antlr3/tree/master/runtime/Python

Follow the instructions in the readme file. It is basically the classic `python setup.py install`.

After that, you have to install pyfuzzy. It can be downloaded from here:

https://sourceforge.net/projects/pyfuzzy/files/pyfuzzy/pyfuzzy-0.1.0/

Unzip the file and install the package using `python setup.py install`.

Finally, use `pip install fst-pso` to complete fst-pso's installation. Please let me know if this procedure works.

Note: * We have implemented a new Sugeno fuzzy logic reasoner in order to remove the dependency on ANTL3+pyfuzzy. It will be supported by the next version of fst-pso, that will be released in a few weeks. This new version will also support python 3.

**Comment by haskarb** [comment]
Hi @aresio !

Thanks for your prompt reply.

I did the installation in the manner you prescribe, but sadly not progress. I am attaching the error snapshot. Please let me know how to handle this.



![image](https://user-images.githubusercontent.com/20501023/39226661-6e808f42-4871-11e8-899d-c3f99043de5b.png)

![image](https://user-images.githubusercontent.com/20501023/39226990-a9ee193a-4873-11e8-8661-cdc11343ab2a.png)

**Comment by aresio** [comment]
Dear Bhaskar, 

it seems that the antlr runtime 3.4 is not fully compatible with pyfuzzy. I will investigate the issue more in depth in the next hours. Meanwhile, could you please give a try to antlr-python-runtime version 3.1.3?

**Comment by haskarb** [comment]
Ok. I will try and let you know. Thanks for replying.

**Comment by UKonge** [comment]
I have tried with 3.1.3 version. For me, it gave similar error.  I have also posted it on stackoverflow (https://stackoverflow.com/questions/49443086/antlr3-python-runtime-not-detected).

**Comment by aresio** [comment]
Hi guys, 

I just uploaded fst-pso version 1.4, which removes the pyfuzzy and ANTL3 dependencies. 

Please, pip install the new version and, if you want, let me know if it works correctly on your systems.

**Comment by UKonge** [comment]
Hi Marco,
I am successfully able to import the fstpso module. Thanks for your prompt help.

**Comment by aresio** [comment]
I apologize, please download version 1.4.1 because I found a bug in the code due to the previous spurious dependencies

**Comment by haskarb** [comment]
Thanks @aresio , it works! I am closing this issue now. 

For those new visitors here, please do` pip install fst-pso`
