### ISSUE TITLE
How to pass arguments to the fitness function?

### ISSUE THREAD

**Issue by haskarb** [aresio/fst-pso#4]
I want to pass some argument along with another parameter to be optimized

For example: How to pass arg1 and arg2 from the `main` function to `example_fitness`

`
def example_fitness( arg1, arg2, particle ):

	return sum(map(lambda x: x**2+ arg1+arg2, particle))
	
```
if __name__ == '__main__':
	dims = 10
	FP = FuzzyPSO()
	FP.set_search_space( [[-10, 10]]*dims )	
	FP.set_fitness(example_fitness)
	result =  FP.solve_with_fstpso()
	print "Best solution:", result[0]
	print "Whose fitness is:", result[1]
```
Q2. The result[0] is an object type. How do I convert it to list or numpy array?

**Comment by aresio** [comment]
Hi, 

Q1) in order to pass optional arguments (that are not part of the candidate solution) to fst-pso you need to encapsulate them in a single object (e.g., a list, array, dictionary). For instance:

```
def example_fitness( particle, args ):
	return sum(map(lambda x: x**2+ args[0] + args[1], particle))

if __name__ == '__main__':
	dims = 10
	FP = FuzzyPSO()
	FP.set_search_space( [[-10, 10]]*dims )	
	FP.set_fitness(example_fitness, arguments=[3.14, 2.58])
	result =  FP.solve_with_fstpso()
	print "Best solution:", result[0]
	print "Whose fitness is:", result[1]
```

Q2) Result[0] is a particle object, carrying all the information about that individual. You can extract the bare structure by accessing `result[0].X `

**Comment by haskarb** [comment]
Thanks for the reply.
